version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      database:
        condition: service_healthy
    environment:
      - DB_HOST=database
      - DB_USER=retro_user
      - DB_PASSWORD=retro_password
      - DB_NAME=retro_games_catalog
      - PORT=3000
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - app-network
    restart: unless-stopped

  # Database service
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3307:3306"  # Changed from 3306:3306 to 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=retro_password
      - MYSQL_DATABASE=retro_games_catalog
      - MYSQL_USER=retro_user
      - MYSQL_PASSWORD=retro_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "retro_user", "-pretro_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  # Message consumer service
  message-consumer:
    build:
      context: ./message-consumer
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      backend:
        condition: service_started
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - BACKEND_URL=http://backend:3000
    networks:
      - app-network
    restart: unless-stopped

  # Message producer service
  message-producer:
    build:
      context: ./message-producer
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - PORT=3001
    networks:
      - app-network
    restart: unless-stopped

# Define networks
networks:
  app-network:
    driver: bridge

# Define volumes
volumes:
  mysql-data:
    driver: local
  rabbitmq-data:
    driver: local
